### ISSUE TITLE
Cannot run script

### ISSUE THREAD

**Issue by Moamethic** [ostenbom/dot-to-dot#3]
~/dot-to-dot# python Main.py /root/photo_2020-05-28_23-40-58.jpg
Traceback (most recent call last):
  File "Main.py", line 3, in <module>
    from DotToDot import makeDotToDot, makeMaxSizeDot
  File "/root/dot-to-dot/DotToDot.py", line 6, in <module>
    from EdgeDetector import EdgeDetector
  File "/root/dot-to-dot/EdgeDetector.py", line 3, in <module>
    import cv2
  File "/usr/local/lib/python2.7/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory

How can I fix this?

**Comment by abelparia** [comment]
run this script: pip install opencv-python
